<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AcademyGroup</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AcademyGroup\AcademyGroup.csproj" />
      <ProjectReference Include="..\MyMenu\MyMenu.csproj" />
    </ItemGroup>

</Project>
